/*
 * SIGGRAPH 2026 itinerary data
 *
 * Future updates should normally touch this file only. Keep dates in YYYY-MM-DD
 * form and times in 24-hour Los Angeles conference time. An event may provide
 * an explicit interest map with 0–4 values for `me` (Ben) and `brother`
 * (Steve); otherwise the UI derives interest from `people` and `status`.
 */

window.ITINERARY_DATA = {
  updatedAt: "2026-07-17T19:45:03-04:00",
  conference: {
    name: "SIGGRAPH 2026",
    subtitle: "Ben + Steve at SIGGRAPH 2026",
    city: "Los Angeles, California",
    venue: "Los Angeles Convention Center",
    address: "1201 S Figueroa St, Los Angeles, CA 90015",
    startDate: "2026-07-19",
    endDate: "2026-07-23",
    timeZone: "America/Los_Angeles",
    timeZoneLabel: "PDT",
    scheduleUrl: "https://s2026.conference-schedule.org/"
  },

  travelers: [
    {
      id: "me",
      label: "Ben",
      name: "Ben Williams",
      badge: "Full Conference",
      focus: "3D Gaussian Splatting, neural rendering, capture pipelines",
      color: "#e55d3f"
    },
    {
      id: "brother",
      label: "Steve",
      name: "Steve",
      badge: "Full Conference (likely)",
      focus: "Performance, voice, virtual theatre, storytelling, education",
      color: "#2d6f70"
    }
  ],

  logistics: [
    {
      id: "outbound",
      icon: "↗",
      eyebrow: "Outbound flight",
      title: "American · CLT → LAX",
      status: "Considering",
      lines: ["Sun, Jul 19 · arrive CLT 7:00 a.m. EDT", "Flight: 8:57 a.m. EDT → 10:56 a.m. PDT", "Nonstop · 4h 59m · Basic Economy"],
      note: "$526 per person round trip · $1,052 total. Flight numbers are not visible in the screenshot."
    },
    {
      id: "hotel",
      icon: "■",
      eyebrow: "Stay",
      title: "Hotel in Los Angeles",
      status: "TBD",
      lines: ["Hotel name", "Address", "Check-in / confirmation"],
      note: "Prefer an official conference hotel or somewhere walkable to LACC."
    },
    {
      id: "return",
      icon: "↙",
      eyebrow: "Return flight",
      title: "American · LAX → CLT",
      status: "Considering",
      lines: ["Sat, Jul 25 · confirm date", "11:00 a.m. PDT → 7:00 p.m. EDT", "Nonstop · 5h 00m · Basic Economy"],
      note: "The date comes from the earlier Jul 19–25 search; it is not visible in the attached fare screenshot."
    }
  ],

  days: [
    { date: "2026-07-19", short: "Sun", label: "Sunday", theme: "Arrival & orientation" },
    { date: "2026-07-20", short: "Mon", label: "Monday", theme: "Research, education & first splats" },
    { date: "2026-07-21", short: "Tue", label: "Tuesday", theme: "The big overlap day" },
    { date: "2026-07-22", short: "Wed", label: "Wednesday", theme: "Animation, capture & performance" },
    { date: "2026-07-23", short: "Thu", label: "Thursday", theme: "Worlds, reconstruction & wrap-up" },
    { date: "2026-07-25", short: "Sat", label: "Saturday", theme: "Tentative flight home" }
  ],

  events: [
    // Sunday
    {
      id: "sun-outbound-flight",
      date: "2026-07-19",
      start: "04:00",
      end: "10:56",
      displayStart: "7:00a EDT",
      displayEnd: "10:56a PDT",
      title: "Arrive CLT · American Airlines to LAX",
      subtitle: "Flight departs 8:57 a.m. EDT · lands 10:56 a.m. PDT",
      type: "Tentative travel",
      location: "CLT → LAX",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      note: "Airport arrival and landing are shown in their local time zones; overlap calculations still use Los Angeles time."
    },
    {
      id: "sun-lax-transfer",
      date: "2026-07-19",
      start: "10:56",
      end: "12:30",
      title: "Land at LAX & head to the convention center",
      subtitle: "Allow for deplaning, bags, pickup and Sunday traffic",
      type: "Travel buffer",
      location: "LAX → LACC",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      note: "Tentative planning block; adjust once the flight, bags and hotel are confirmed."
    },
    {
      id: "sun-game-audio",
      date: "2026-07-19",
      start: "10:45",
      end: "11:15",
      title: "Game Audio Lasagna",
      subtitle: "Building layers to create new sonic worlds",
      type: "Games Summit",
      location: "411 Theatre",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "Steve would still be in flight on the tentative itinerary."
    },
    {
      id: "sun-animation-theater",
      date: "2026-07-19",
      start: "12:30",
      end: "13:30",
      title: "Animation Theater 1: Open Worlds",
      type: "Computer Animation Festival",
      location: "411 Theatre",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "A useful creative reset, but 12:30 p.m. is a stretch after an LAX arrival."
    },
    {
      id: "sun-performance-capture",
      date: "2026-07-19",
      start: "13:45",
      end: "14:15",
      title: "Performance Capture at Scale",
      subtitle: "Building a pipeline for Battlefield 6 cinematics",
      type: "Games Summit",
      location: "411 Theatre",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "One of Sunday's clearest bridges between acting and digital production."
    },
    {
      id: "sun-tyree",
      date: "2026-07-19",
      start: "14:00",
      end: "15:30",
      title: "In Conversation with Tyree Dillihay",
      type: "Computer Animation Festival",
      location: "Petree D",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Full-only conversation with an animation director; promising for directing and performance perspective."
    },
    {
      id: "sun-career",
      date: "2026-07-19",
      start: "14:15",
      end: "15:15",
      title: "Resume, Reel & Industry Insights",
      subtitle: "Kickstart a career in computer graphics",
      type: "Career development",
      location: "Room 404 AB",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "Not voice-acting-specific, but useful for translating a non-linear creative career into a portfolio."
    },
    {
      id: "sun-stage-presence",
      date: "2026-07-19",
      start: "16:25",
      end: "16:45",
      title: "Stage Presence",
      subtitle: "Design and testing of a virtual rehearsal room toolset",
      type: "Talk",
      location: "Room 403 B",
      people: ["brother"],
      access: ["Full"],
      status: "recommended",
      note: "The most directly theatre-specific Full-only item: distributed rehearsal, spatial memory and performer agency.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_323&sess=sess183"
    },
    {
      id: "sun-machine-choreographies",
      date: "2026-07-19",
      start: "17:00",
      end: "17:30",
      title: "Machine Choreographies",
      subtitle: "AI, dance and the future of embodied performance",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "A strong late-Sunday target if the flight arrives that afternoon."
    },
    {
      id: "sun-badge-pickup",
      date: "2026-07-19",
      start: "12:30",
      end: "13:00",
      title: "Badge pickup & luggage check",
      type: "Logistics",
      location: "West Hall A",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      note: "Tentative arrival target. Sunday registration and attendee services close at 6:00 p.m."
    },
    {
      id: "sun-gaussian-posters",
      date: "2026-07-19",
      start: "13:00",
      end: "17:30",
      title: "3DGS poster sweep",
      subtitle: "RaDe-GS, densification, temporal GS, continual learning and reactive splats",
      type: "Posters · drop in",
      location: "West Hall Lobby",
      people: ["me", "brother"],
      interest: { me: 4, brother: 1 },
      access: ["Experience", "Full"],
      status: "drop-in",
      note: "The poster displays run all afternoon, so Ben can browse them between fixed sessions.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess431"
    },
    {
      id: "sun-performance-posters",
      date: "2026-07-19",
      start: "13:00",
      end: "17:30",
      title: "Performance & animation poster sweep",
      subtitle: "Speech-driven facial animation, motion, choreography and immersive storytelling",
      type: "Posters · drop in",
      location: "West Hall Lobby",
      people: ["me", "brother"],
      interest: { me: 1, brother: 3 },
      access: ["Experience", "Full"],
      status: "drop-in",
      note: "A flexible Steve track while Ben explores the 3D and rendering posters.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess453"
    },
    {
      id: "sun-beyond-3d",
      date: "2026-07-19",
      start: "14:00",
      end: "17:15",
      title: "NVIDIA: Beyond 3D",
      subtitle: "From real-world objects to digital assets and physical AI",
      type: "Course",
      location: "Room 403 A",
      people: ["me"],
      interest: { me: 3, brother: 0 },
      access: ["Full"],
      status: "recommended",
      note: "Capture, scanning, digital twins and simulation make this adjacent to Ben's reconstruction work."
    },
    {
      id: "sun-between-frames",
      date: "2026-07-19",
      start: "14:00",
      end: "15:30",
      title: "Between the Frames",
      subtitle: "Rotoscoping, anime in-betweening and AI-assisted animation",
      type: "Talks",
      location: "Room 403 B",
      people: ["me", "brother"],
      interest: { me: 1, brother: 3 },
      access: ["Full"],
      status: "recommended",
      note: "A reachable Full Conference block with clear links to performance and animation workflows.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess172"
    },
    {
      id: "sun-beginners",
      date: "2026-07-19",
      start: "15:30",
      end: "16:30",
      title: "SIGGRAPH for Beginners",
      subtitle: "Welcome to the conference",
      type: "ACM SIGGRAPH 365",
      location: "Room 404 AB",
      people: ["me", "brother"],
      interest: { me: 2, brother: 2 },
      access: ["Experience", "Full"],
      status: "option",
      note: "Useful first-conference orientation if the competing technical and performance sessions are less compelling."
    },
    {
      id: "sun-openusd",
      date: "2026-07-19",
      start: "15:45",
      end: "17:15",
      title: "The OpenUSD Roundtable",
      subtitle: "Open-source pipelines across film and game development",
      type: "Games Summit",
      location: "411 Theatre",
      people: ["me", "brother"],
      interest: { me: 3, brother: 1 },
      access: ["Experience", "Full"],
      status: "recommended",
      note: "A practical pipeline discussion that complements Ben's 3DGS and interchange interests."
    },
    {
      id: "sun-wizard-oz-sphere",
      date: "2026-07-19",
      start: "16:15",
      end: "17:15",
      title: "The Wizard of Oz at Sphere",
      subtitle: "Scaling generative AI for a 16K immersive production",
      type: "Production Session",
      location: "Petree D",
      people: ["me", "brother"],
      interest: { me: 2, brother: 4 },
      access: ["Full"],
      status: "recommended",
      note: "A strong Steve pick: performance continuity, immersive staging and hybrid VFX production.",
      url: "https://s2026.conference-schedule.org/presentation/?id=pros_114&sess=sess159"
    },
    {
      id: "sun-papers-fast-forward",
      date: "2026-07-19",
      start: "18:00",
      end: "20:45",
      title: "Papers Fast Forward",
      subtitle: "A rapid preview of the Technical Papers program",
      type: "Technical Papers",
      location: "Hall K",
      people: ["me", "brother"],
      interest: { me: 4, brother: 2 },
      access: ["Experience", "Full"],
      status: "anchor",
      note: "A must for the splat paper previews; also a useful way for both travelers to survey the week."
    },

    // Monday
    {
      id: "mon-opening",
      date: "2026-07-20",
      start: "09:00",
      end: "10:30",
      title: "Opening Session & Lanny Smoot Keynote",
      type: "Keynote",
      location: "Hall K",
      people: ["me", "brother"],
      interest: { me: 2, brother: 2 },
      access: ["Discover", "Experience", "Full"],
      status: "option",
      note: "Shared opening before the schedules diverge."
    },
    {
      id: "mon-educator-careers",
      date: "2026-07-20",
      start: "10:15",
      end: "10:45",
      title: "Preparing Students for Creative Careers",
      subtitle: "Teaching the tools and workflows industry uses",
      type: "Educator's Day",
      location: "Room 411",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Directly relevant to Steve's former theatre-education work."
    },
    {
      id: "mon-impulse",
      date: "2026-07-20",
      start: "10:30",
      end: "17:00",
      title: "Impulse: Dawn of the Digital Dance Studio",
      subtitle: "Hands-on motion capture and digital choreography",
      type: "Immersive Pavilion",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "drop-in",
      note: "Drop in between sessions to record movement and apply it to digital dancers."
    },
    {
      id: "mon-ai-education",
      date: "2026-07-20",
      start: "11:00",
      end: "12:00",
      title: "How AI Is Changing Education",
      type: "Educator's Day",
      location: "Room 411",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "Useful context if Steve returns to arts education."
    },
    {
      id: "mon-3dgs-1",
      date: "2026-07-20",
      start: "14:00",
      end: "15:30",
      title: "3D Gaussian Splatting I",
      type: "Technical Papers",
      location: "Room 408 A",
      people: ["me"],
      access: ["Full"],
      status: "anchor",
      note: "Core paper block and a top priority now that Ben has Full Conference access.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess137"
    },
    {
      id: "mon-avatar",
      date: "2026-07-20",
      start: "14:30",
      end: "15:30",
      title: "Avatar: Fire and Ash",
      subtitle: "Performance capture, facial motion and production at scale",
      type: "Production Session",
      location: "Hall K",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "A strong Full-only look at preserving actor intent across 2,500 facial-motion shots.",
      url: "https://s2026.conference-schedule.org/presentation/?id=pros_106&sess=sess160"
    },
    {
      id: "mon-web-3dgs",
      date: "2026-07-20",
      start: "15:00",
      end: "15:45",
      title: "3DGS in Web Gaming",
      subtitle: "The Shadow of the Czar",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "The first explicit Experience-accessible 3DGS session."
    },
    {
      id: "mon-powered-splats",
      date: "2026-07-20",
      start: "15:30",
      end: "17:00",
      title: "Powered by Gaussian Splats",
      subtitle: "From world models to interactive 3D worlds",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Full"],
      status: "wishlist",
      note: "Full-only and directly useful, but overlaps the end of the web-gaming presentation."
    },
    {
      id: "mon-electronic-theater",
      date: "2026-07-20",
      start: "18:30",
      end: "20:30",
      title: "Electronic Theater",
      subtitle: "Separate ticket required",
      type: "Computer Animation Festival",
      location: "Hall K",
      people: ["me", "brother"],
      interest: { me: 2, brother: 3 },
      access: ["Add-on"],
      status: "option",
      note: "Shared evening option. Experience and Discover attendees can add a $60 ticket."
    },

    // Tuesday
    {
      id: "tue-splats-worlds",
      date: "2026-07-21",
      start: "08:30",
      end: "10:00",
      title: "From Splats to Worlds",
      subtitle: "Advanced 3DGS applications",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Top-priority community session."
    },
    {
      id: "tue-zootopia",
      date: "2026-07-21",
      start: "09:30",
      end: "10:30",
      title: "Developing the Worlds and Characters of Zootopia 2",
      type: "Production Session",
      location: "Hall K",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Full-only animation and character-development option."
    },
    {
      id: "tue-chaos-ray-traced",
      date: "2026-07-21",
      start: "10:00",
      end: "10:50",
      title: "Ray-Traced Gaussian Splats in Production",
      subtitle: "The June July pipeline",
      type: "Industry Session",
      location: "Room 511 C",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "anchor",
      note: "Production-focused splat pipeline from Chaos.",
      url: "https://s2026.conference-schedule.org/presentation/?id=ind_113&sess=sess511"
    },
    {
      id: "tue-inside-show",
      date: "2026-07-21",
      start: "10:15",
      end: "11:00",
      title: "Inside the Show",
      subtitle: "A live VR performance and its backstage systems",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Live acting in VR followed by a reveal of actor menus, triggers and show controls.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_347&sess=sess373"
    },
    {
      id: "tue-brad-bird",
      date: "2026-07-21",
      start: "10:45",
      end: "12:15",
      title: "In Conversation with Brad Bird",
      subtitle: "Storytelling, creative vision and Ray Gunn",
      type: "Computer Animation Festival",
      location: "Hall K",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Excellent for directing and storytelling, but it conflicts with the more voice-specific Expanded Voices.",
      url: "https://s2026.conference-schedule.org/presentation/?id=cafcur_102&sess=sess488"
    },
    {
      id: "tue-expanded-voices",
      date: "2026-07-21",
      start: "11:05",
      end: "11:25",
      title: "Expanded Voices",
      subtitle: "Voice cloning, latent spaces and embodied translation",
      type: "Art Paper",
      location: "411 Theatre",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "The week's most directly voice-related session, focused on cloning, identity, embodiment and authorship.",
      url: "https://s2026.conference-schedule.org/presentation/?id=artpl_135&sess=sess229"
    },
    {
      id: "tue-chaos-latest",
      date: "2026-07-21",
      start: "11:00",
      end: "11:50",
      title: "What's the Latest at Chaos?",
      subtitle: "World-building, Gaussian splats and artist-friendly AI",
      type: "Industry Session",
      location: "Room 511 C",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "recommended",
      note: "A second practical Chaos session immediately after the ray-traced splat talk."
    },
    {
      id: "tue-live-from-la",
      date: "2026-07-21",
      start: "14:00",
      end: "14:20",
      title: "Live from LA!",
      subtitle: "Immersive youth theatre and personal storytelling",
      type: "Educator's Forum",
      location: "Room 501 ABC",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Dance, poetry, projection mapping and p5.js in a youth-theatre production.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_395&sess=sess209"
    },
    {
      id: "tue-radiance-fields",
      date: "2026-07-21",
      start: "14:30",
      end: "16:00",
      title: "Deploying Radiance Fields Across Real-Time and Web",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Industry/research bridge and one of the most valuable Experience sessions."
    },
    {
      id: "tue-lod-gaussians",
      date: "2026-07-21",
      start: "14:40",
      end: "15:40",
      title: "A LoD of Gaussians",
      subtitle: "Out-of-core training and rendering for ultra-large scenes",
      type: "Emerging Technologies Demo",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "option",
      note: "Drop-in demo that overlaps Deploying Radiance Fields."
    },
    {
      id: "tue-nurec",
      date: "2026-07-21",
      start: "15:00",
      end: "15:50",
      title: "Autonomous Vehicle Simulation with NuRec, 3D Gaussian & Cosmos",
      type: "Industry Session",
      location: "Room 502 A",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "option",
      note: "Another overlapping option; prioritize based on whether deployment or simulation matters more."
    },
    {
      id: "tue-roll-reality",
      date: "2026-07-21",
      start: "15:15",
      end: "17:00",
      title: "Roll for Reality",
      subtitle: "Virtual-production improvised D&D show",
      type: "Immersive Pavilion",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Live improvisation combining tabletop performance, motion capture, AI narrative and real-time XR.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensubcur105&sess=sess380"
    },

    // Wednesday
    {
      id: "wed-hiring",
      date: "2026-07-22",
      start: "09:00",
      end: "10:30",
      title: "Current Hiring Trends in Animation & VFX",
      type: "Educator's Forum",
      location: "Room 501 ABC",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Useful market context, even if voice work itself is not the focus."
    },
    {
      id: "wed-gausmoke",
      date: "2026-07-22",
      start: "10:00",
      end: "11:00",
      title: "GauSmoke",
      subtitle: "Hybrid physics-optical Gaussian splatting for smoke reconstruction",
      type: "Emerging Technologies Demo",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Drop-in technical demo."
    },
    {
      id: "wed-splats-animation",
      date: "2026-07-22",
      start: "10:00",
      end: "11:30",
      title: "Gaussian Splatting for Animation",
      subtitle: "Emerging workflows and hybrid pipelines",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Prefer this over the overlapping demos unless a specific presenter is essential."
    },
    {
      id: "wed-motion-capture-society",
      date: "2026-07-22",
      start: "11:00",
      end: "12:00",
      title: "Motion Capture Society",
      type: "Birds of a Feather",
      location: "Room 512",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Direct professional community around performance capture."
    },
    {
      id: "wed-openusd-streamed",
      date: "2026-07-22",
      start: "11:30",
      end: "12:00",
      title: "OpenUSD Streamed to Any Device",
      type: "Stage Session",
      location: "West Hall A",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "option",
      note: "Radiance-field-adjacent delivery workflow."
    },
    {
      id: "wed-virtual-theatre",
      date: "2026-07-22",
      start: "13:00",
      end: "13:45",
      title: "Virtual Theatre",
      subtitle: "Producing live theatre on virtual stages",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "The clearest Experience-level match for Steve's theatre-company background."
    },
    {
      id: "wed-cheap-cheerful",
      date: "2026-07-22",
      start: "14:00",
      end: "14:35",
      title: "Cheap and Cheerful",
      subtitle: "Low-fidelity prototyping for spatial stories",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Potentially useful for making ambitious work with home-studio resources."
    },
    {
      id: "wed-refact",
      date: "2026-07-22",
      start: "15:00",
      end: "15:45",
      title: "REfact: Growing with Movement",
      subtitle: "A hybrid performance",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "Performance-first option before the late-afternoon conflict."
    },
    {
      id: "wed-ai-mocap",
      date: "2026-07-22",
      start: "15:30",
      end: "17:00",
      title: "From Footage to Previs",
      subtitle: "Hands-on AI mocap workflows with Autodesk Flow Studio and Maya",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Practical choice; overlaps the Full-only facial-performance talks."
    },
    {
      id: "wed-show-feelings",
      date: "2026-07-22",
      start: "15:45",
      end: "17:05",
      title: "Show Your Feelings",
      subtitle: "Predator, Rigs2Emotion and Avatar facial performance",
      type: "Talks",
      location: "Room 515 A",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "The strongest Full-only performance-to-digital-character block.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess174"
    },
    {
      id: "wed-printing",
      date: "2026-07-22",
      start: "17:25",
      end: "17:45",
      title: "Printing the Underdetermined",
      subtitle: "Materializing uncertainty through 3D Gaussian Splatting",
      type: "Art Paper",
      location: "411 Theatre",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "An art/research crossover using multiple 3DGS reconstructions and volumetric printing.",
      url: "https://s2026.conference-schedule.org/presentation/?id=artps_121&sess=sess231"
    },

    // Thursday
    {
      id: "thu-geospatial",
      date: "2026-07-23",
      start: "09:00",
      end: "10:00",
      title: "Geospatial and 3D Tiles",
      type: "Birds of a Feather",
      location: "Room 518",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Includes discussion of large-scale geospatial content and splat delivery."
    },
    {
      id: "thu-resume-reel",
      date: "2026-07-23",
      start: "09:00",
      end: "10:00",
      title: "How to Get Your Resume & Reel Noticed",
      type: "Career development",
      location: "Room 404 AB",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "A second chance if Sunday's career session is lost to travel."
    },
    {
      id: "thu-captures-environments",
      date: "2026-07-23",
      start: "10:15",
      end: "11:45",
      title: "From 3D Captures to Simulated Digital Environments",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "NVIDIA capture-to-simulation pipeline with mixed splat/mesh physics."
    },
    {
      id: "thu-dear-neighbors",
      date: "2026-07-23",
      start: "11:15",
      end: "12:15",
      title: "Dear Upstairs Neighbors",
      subtitle: "Artist-centered, AI-assisted expressionistic animation",
      type: "Production Session",
      location: "Petree D",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Director, VFX supervisor and animator discuss keeping artists in control of generative workflows.",
      url: "https://s2026.conference-schedule.org/presentation/?id=pros_109&sess=sess161"
    },
    {
      id: "thu-world-simulation",
      date: "2026-07-23",
      start: "12:00",
      end: "13:30",
      title: "Advance World Simulation with 3D Gaussian Splatting",
      subtitle: "Large-scale environment reconstruction",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "The week's clearest Experience-level hands-on 3DGS course.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_527&sess=sess265"
    },
    {
      id: "thu-educator-townhall",
      date: "2026-07-23",
      start: "12:30",
      end: "13:30",
      title: "Educator's Townhall",
      type: "Educator's Forum",
      location: "Room 409 AB",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "A natural networking and reflection session for Steve's theatre-education background."
    },
    {
      id: "thu-3dgs-2",
      date: "2026-07-23",
      start: "14:00",
      end: "15:30",
      title: "3D Gaussian Splatting II",
      type: "Technical Papers",
      location: "Room 408 A",
      people: ["me"],
      access: ["Full"],
      status: "anchor",
      note: "Second core 3DGS paper block and a top priority with Full Conference access.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess136"
    },
    {
      id: "thu-multimodal",
      date: "2026-07-23",
      start: "15:45",
      end: "17:15",
      title: "Multimodal Learning",
      subtitle: "Dialogue, generated audio and automatic dubbing",
      type: "Technical Papers",
      location: "Room 403 A",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Technical rather than practical, but highly relevant to technologies reshaping voice work.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess101"
    },
    {
      id: "thu-gaussian-reconstruction",
      date: "2026-07-23",
      start: "15:45",
      end: "17:15",
      title: "Gaussian Reconstruction",
      type: "Technical Papers",
      location: "Room 408 B",
      people: ["me"],
      access: ["Full"],
      status: "anchor",
      note: "Final major splat session and a top priority with Full Conference access.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess138"
    },

    // Saturday travel
    {
      id: "sat-return-flight",
      date: "2026-07-25",
      start: "11:00",
      end: "16:00",
      title: "American Airlines · LAX → CLT",
      subtitle: "Departs 11:00 a.m. PDT · lands 7:00 p.m. EDT",
      type: "Tentative flight",
      location: "LAX → CLT",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      note: "Nonstop · 5h 00m · Basic Economy. July 25 comes from the earlier search and still needs confirmation."
    }
  ]
};
