/*
 * SIGGRAPH 2026 itinerary data
 *
 * Future updates should normally touch this file only. Keep dates in YYYY-MM-DD
 * form and times in 24-hour Los Angeles conference time. An event may provide
 * an explicit interest map with 0–4 values for `me` (Ben) and `brother`
 * (Steve); otherwise the UI derives interest from `people` and `status`.
 * Shared logistics may set `showInterest: false` to omit preference bars.
 */

window.ITINERARY_DATA = {
  updatedAt: "2026-07-18T09:41:00-04:00",
  conference: {
    name: "SIGGRAPH 2026",
    subtitle: "Ben + Steve at SIGGRAPH 2026",
    city: "Los Angeles, California",
    venue: "Los Angeles Convention Center",
    address: "1201 S Figueroa St, Los Angeles, CA 90015",
    startDate: "2026-07-19",
    endDate: "2026-07-23",
    timeZone: "America/Los_Angeles",
    timeZoneLabel: "PDT",
    scheduleUrl: "https://s2026.conference-schedule.org/"
  },

  travelers: [
    {
      id: "me",
      label: "Ben",
      name: "Ben Williams",
      badge: "Full Conference",
      focus: "3D Gaussian Splatting, neural rendering, capture pipelines",
      color: "#e55d3f"
    },
    {
      id: "brother",
      label: "Steve",
      name: "Steve",
      badge: "Full Conference (likely)",
      focus: "Performance, voice, virtual theatre, storytelling, education",
      color: "#2d6f70"
    }
  ],

  logistics: [
    {
      id: "outbound",
      icon: "↗",
      eyebrow: "Outbound flight",
      title: "American · CLT → LAX",
      status: "Confirmed",
      lines: ["Sun, Jul 19 · at CLT by 7:00 a.m. EDT", "AA 1995 · 8:57 a.m. EDT → 10:56 a.m. PDT", "Nonstop · 4h 59m · Basic Economy"],
      links: [
        { label: "Track AA 1995", url: "https://www.flightaware.com/live/flight/AAL1995" },
        { label: "CLT", url: "https://www.google.com/maps/search/?api=1&query=Charlotte+Douglas+International+Airport" },
        { label: "LAX", url: "https://www.google.com/maps/search/?api=1&query=Los+Angeles+International+Airport" }
      ],
      note: "Check-in opens 24 hours before departure in the AA app."
    },
    {
      id: "hotel",
      icon: "■",
      eyebrow: "Stay",
      title: "Hotel in Los Angeles",
      status: "TBD",
      lines: ["Hotel name", "Address", "Check-in time"],
      links: [
        { label: "LACC", url: "https://www.google.com/maps/search/?api=1&query=Los+Angeles+Convention+Center" }
      ],
      note: "Prefer an official conference hotel or somewhere walkable to LACC."
    },
    {
      id: "return",
      icon: "↙",
      eyebrow: "Return flight",
      title: "American · LAX → CLT",
      status: "Confirmed",
      lines: ["Sat, Jul 25", "AA 1159 · 11:00 a.m. PDT → 7:00 p.m. EDT", "Nonstop · 5h 00m · Basic Economy"],
      links: [
        { label: "Track AA 1159", url: "https://www.flightaware.com/live/flight/AAL1159" },
        { label: "LAX", url: "https://www.google.com/maps/search/?api=1&query=Los+Angeles+International+Airport" }
      ],
      note: "Aim for LAX by 9:00 a.m. with bags. Check-in opens 24 hours before departure in the AA app."
    }
  ],

  days: [
    { date: "2026-07-19", short: "Sun", label: "Sunday", theme: "Arrival & orientation" },
    { date: "2026-07-20", short: "Mon", label: "Monday", theme: "Research, education & first splats" },
    { date: "2026-07-21", short: "Tue", label: "Tuesday", theme: "The big overlap day" },
    { date: "2026-07-22", short: "Wed", label: "Wednesday", theme: "Animation, capture & performance" },
    { date: "2026-07-23", short: "Thu", label: "Thursday", theme: "Worlds, reconstruction & wrap-up" },
    { date: "2026-07-24", short: "Fri", label: "Friday", theme: "Free day in Los Angeles" },
    { date: "2026-07-25", short: "Sat", label: "Saturday", theme: "Flight home" }
  ],

  events: [
    // Sunday
    {
      id: "sun-outbound-flight",
      date: "2026-07-19",
      start: "04:00",
      end: "10:56",
      displayStart: "7:00a EDT",
      displayEnd: "10:56a PDT",
      title: "Morning flight · Charlotte to Los Angeles",
      subtitle: "At CLT by 7:00 a.m. · departs 8:57 a.m. EDT · lands 10:56 a.m. PDT",
      type: "Confirmed flight",
      location: "CLT → LAX",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      showInterest: false,
      note: "Times are shown in each airport’s local zone; overlap checks still use Los Angeles time."
    },
    {
      id: "sun-lax-transfer",
      date: "2026-07-19",
      start: "10:56",
      end: "12:30",
      title: "Land at LAX & head to the convention center",
      subtitle: "Allow for deplaning, bags, pickup and Sunday traffic",
      type: "Travel buffer",
      location: "LAX → LACC",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      showInterest: false,
      note: "Planning buffer; adjust for bags, pickup and the hotel once those details are known."
    },
    {
      id: "sun-performance-capture",
      date: "2026-07-19",
      start: "13:45",
      end: "14:15",
      title: "Performance Capture at Scale",
      subtitle: "Building a pipeline for Battlefield 6 cinematics",
      type: "Games Summit",
      location: "411 Theatre",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Pipeline walkthrough from capture stage to finished cinematic."
    },
    {
      id: "sun-tyree",
      date: "2026-07-19",
      start: "14:00",
      end: "15:30",
      title: "In Conversation with Tyree Dillihay",
      type: "Computer Animation Festival",
      location: "Petree D",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "A moderated conversation with animation director Tyree Dillihay. Full badge only."
    },
    {
      id: "sun-career",
      date: "2026-07-19",
      start: "14:15",
      end: "15:15",
      title: "Resume, Reel & Industry Insights",
      subtitle: "Kickstart a career in computer graphics",
      type: "Career development",
      location: "Room 404 AB",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "Practical resume and demo-reel guidance. Not voice-specific."
    },
    {
      id: "sun-stage-presence",
      date: "2026-07-19",
      start: "16:25",
      end: "16:45",
      title: "Stage Presence",
      subtitle: "Design and testing of a virtual rehearsal room toolset",
      type: "Talk",
      location: "Room 403 B",
      people: ["brother"],
      access: ["Full"],
      status: "recommended",
      note: "Agile Lens presents a multi-user XR rehearsal platform, evaluated with professional theatre makers: distributed rehearsal, spatial memory, performer agency. Full badge only.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_323&sess=sess183"
    },
    {
      id: "sun-machine-choreographies",
      date: "2026-07-19",
      start: "17:00",
      end: "17:30",
      title: "Machine Choreographies",
      subtitle: "AI, dance and the future of embodied performance",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Open community discussion on AI choreography and embodied performance. Late enough to make even with an afternoon arrival."
    },
    {
      id: "sun-badge-pickup",
      date: "2026-07-19",
      start: "12:30",
      end: "13:00",
      title: "Badge pickup & luggage check",
      type: "Logistics",
      location: "West Hall A",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      showInterest: false,
      note: "Registration and attendee services close at 6:00 p.m. Sunday."
    },
    {
      id: "sun-gaussian-posters",
      date: "2026-07-19",
      start: "13:00",
      end: "17:30",
      title: "3DGS poster sweep",
      subtitle: "RaDe-GS, densification, temporal GS, continual learning and reactive splats",
      type: "Posters · drop in",
      location: "West Hall Lobby",
      people: ["me", "brother"],
      interest: { me: 4, brother: 1 },
      access: ["Experience", "Full"],
      status: "drop-in",
      note: "Posters up all afternoon, including continual-learning 3DGS under structural and lighting change. Easy to browse between fixed sessions.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess431"
    },
    {
      id: "sun-performance-posters",
      date: "2026-07-19",
      start: "13:00",
      end: "17:30",
      title: "Performance & animation poster sweep",
      subtitle: "Speech-driven facial animation, motion, choreography and immersive storytelling",
      type: "Posters · drop in",
      location: "West Hall Lobby",
      people: ["me", "brother"],
      interest: { me: 1, brother: 3 },
      access: ["Experience", "Full"],
      status: "drop-in",
      note: "Includes speech-driven facial animation in Unreal and Laban-based motion analysis. Same lobby as the 3DGS sweep, all afternoon.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess453"
    },
    {
      id: "sun-beyond-3d",
      date: "2026-07-19",
      start: "14:00",
      end: "17:15",
      title: "NVIDIA: Beyond 3D",
      subtitle: "From real-world objects to digital assets and physical AI",
      type: "Course",
      location: "Room 403 A",
      people: ["me"],
      interest: { me: 3, brother: 0 },
      access: ["Full"],
      status: "recommended",
      note: "Capture, scanning, digital twins and simulation — directly adjacent to 3DGS reconstruction work."
    },
    {
      id: "sun-between-frames",
      date: "2026-07-19",
      start: "14:00",
      end: "15:30",
      title: "Between the Frames",
      subtitle: "Rotoscoping, anime in-betweening and AI-assisted animation",
      type: "Talks",
      location: "Room 403 B",
      people: ["me", "brother"],
      interest: { me: 1, brother: 3 },
      access: ["Full"],
      status: "recommended",
      note: "Four short talks chaired by Disney's Michael Reed: Roto-Lite transformer rotoscoping, anime in-betweening with video models, and a defense of Euler angles. Full badge only.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess172"
    },
    {
      id: "sun-beginners",
      date: "2026-07-19",
      start: "15:30",
      end: "16:30",
      title: "SIGGRAPH for Beginners",
      subtitle: "Welcome to the conference",
      type: "ACM SIGGRAPH 365",
      location: "Room 404 AB",
      people: ["me", "brother"],
      interest: { me: 2, brother: 2 },
      access: ["Experience", "Full"],
      status: "option",
      note: "Orientation on how the conference is organized and how to navigate it. An easy skip if a competing session wins."
    },
    {
      id: "sun-openusd",
      date: "2026-07-19",
      start: "15:45",
      end: "17:15",
      title: "The OpenUSD Roundtable",
      subtitle: "Open-source pipelines across film and game development",
      type: "Games Summit",
      location: "411 Theatre",
      people: ["me", "brother"],
      interest: { me: 3, brother: 1 },
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Roundtable on OpenUSD adoption across film and game pipelines."
    },
    {
      id: "sun-wizard-oz-sphere",
      date: "2026-07-19",
      start: "16:15",
      end: "17:15",
      title: "The Wizard of Oz at Sphere",
      subtitle: "Scaling generative AI for a 16K immersive production",
      type: "Production Session",
      location: "Petree D",
      people: ["me", "brother"],
      interest: { me: 2, brother: 4 },
      access: ["Full"],
      status: "recommended",
      note: "Sphere Studios, Magnopus and Google DeepMind on taking 1939's 4:3 footage to a 16K dome: generative super-resolution, character outpainting and AI performance generation.",
      url: "https://s2026.conference-schedule.org/presentation/?id=pros_114&sess=sess159"
    },
    {
      id: "sun-papers-fast-forward",
      date: "2026-07-19",
      start: "18:00",
      end: "20:45",
      title: "Papers Fast Forward",
      subtitle: "A rapid preview of the Technical Papers program",
      type: "Technical Papers",
      location: "Hall K",
      people: ["me", "brother"],
      interest: { me: 4, brother: 2 },
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Every technical paper pitches itself in seconds, back to back. The fastest survey of the week — splat papers included."
    },

    // Monday
    {
      id: "mon-opening",
      date: "2026-07-20",
      start: "09:00",
      end: "10:30",
      title: "Opening Session & Lanny Smoot Keynote",
      type: "Keynote",
      location: "Hall K",
      people: ["me", "brother"],
      interest: { me: 2, brother: 2 },
      access: ["Discover", "Experience", "Full"],
      status: "option",
      note: "Conference welcome, then a keynote from Disney Imagineer Lanny Smoot."
    },
    {
      id: "mon-educator-careers",
      date: "2026-07-20",
      start: "10:15",
      end: "10:45",
      title: "Preparing Students for Creative Careers",
      subtitle: "Teaching the tools and workflows industry uses",
      type: "Educator's Day",
      location: "Room 411",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Industry tools and workflows through a teaching lens."
    },
    {
      id: "mon-impulse",
      date: "2026-07-20",
      start: "10:30",
      end: "17:00",
      title: "Impulse: Dawn of the Digital Dance Studio",
      subtitle: "Hands-on motion capture and digital choreography",
      type: "Immersive Pavilion",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "drop-in",
      note: "Record movement and apply it to digital dancers — open all day for drop-ins."
    },
    {
      id: "mon-ai-education",
      date: "2026-07-20",
      start: "11:00",
      end: "12:00",
      title: "How AI Is Changing Education",
      type: "Educator's Day",
      location: "Room 411",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "A survey of how AI is landing in classrooms and teaching practice."
    },
    {
      id: "mon-3dgs-1",
      date: "2026-07-20",
      start: "14:00",
      end: "15:30",
      title: "3D Gaussian Splatting I",
      type: "Technical Papers",
      location: "Room 408 A",
      people: ["me"],
      access: ["Full"],
      status: "anchor",
      note: "Papers include structure-aware densification, SHARP-GS ultra-high-res rendering and A LoD of Gaussians for out-of-core scenes. Full badge only.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess137"
    },
    {
      id: "mon-avatar",
      date: "2026-07-20",
      start: "14:30",
      end: "15:30",
      title: "Avatar: Fire and Ash",
      subtitle: "Performance capture, facial motion and production at scale",
      type: "Production Session",
      location: "Hall K",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Wētā FX supervisors on the production: native-stereo virtual cinematography, the new Kora fire solver, and preserving actor intent across 2,500 facial-motion shots. Full badge only.",
      url: "https://s2026.conference-schedule.org/presentation/?id=pros_106&sess=sess160"
    },
    {
      id: "mon-web-3dgs",
      date: "2026-07-20",
      start: "15:00",
      end: "15:45",
      title: "3DGS in Web Gaming",
      subtitle: "The Shadow of the Czar",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Case study of 3DGS shipped in a playable web title."
    },
    {
      id: "mon-powered-splats",
      date: "2026-07-20",
      start: "15:30",
      end: "17:00",
      title: "Powered by Gaussian Splats",
      subtitle: "From world models to interactive 3D worlds",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Full"],
      status: "wishlist",
      note: "Hands-on course on turning world models into interactive 3D worlds. Overlaps the end of the web-gaming session."
    },
    {
      id: "mon-electronic-theater",
      date: "2026-07-20",
      start: "18:30",
      end: "20:30",
      title: "Electronic Theater",
      subtitle: "Separate ticket required",
      type: "Computer Animation Festival",
      location: "Hall K",
      people: ["me", "brother"],
      interest: { me: 2, brother: 3 },
      access: ["Add-on"],
      status: "option",
      note: "The festival's curated evening screening. Experience and Discover badges can add the $60 ticket."
    },

    // Tuesday
    {
      id: "tue-splats-worlds",
      date: "2026-07-21",
      start: "08:30",
      end: "10:00",
      title: "From Splats to Worlds",
      subtitle: "Advanced 3DGS applications",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Open community session on advanced 3DGS applications — practitioners comparing notes."
    },
    {
      id: "tue-zootopia",
      date: "2026-07-21",
      start: "09:30",
      end: "10:30",
      title: "Developing the Worlds and Characters of Zootopia 2",
      type: "Production Session",
      location: "Hall K",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "World and character development process for Zootopia 2. Full badge only."
    },
    {
      id: "tue-chaos-ray-traced",
      date: "2026-07-21",
      start: "10:00",
      end: "10:50",
      title: "Ray-Traced Gaussian Splats in Production",
      subtitle: "The June July pipeline",
      type: "Industry Session",
      location: "Room 511 C",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "anchor",
      note: "Chaos' Chris Nichols on the June July pipeline: location scans from an XGrids scanner and Alexa 35 becoming HDR splats staged in Chaos Arena for lighting and camera planning.",
      url: "https://s2026.conference-schedule.org/presentation/?id=ind_113&sess=sess511"
    },
    {
      id: "tue-inside-show",
      date: "2026-07-21",
      start: "10:15",
      end: "11:00",
      title: "Inside the Show",
      subtitle: "A live VR performance and its backstage systems",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Ferryman Collective performs a short VR scene live, then reveals the backstage systems — triggers, actor menus, show control.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_347&sess=sess373"
    },
    {
      id: "tue-brad-bird",
      date: "2026-07-21",
      start: "10:45",
      end: "12:15",
      title: "In Conversation with Brad Bird",
      subtitle: "Storytelling, creative vision and Ray Gunn",
      type: "Computer Animation Festival",
      location: "Hall K",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Brad Bird on Ray Gunn, his neo-noir animated detective film for Netflix, with unseen development material. Conflicts with Expanded Voices.",
      url: "https://s2026.conference-schedule.org/presentation/?id=cafcur_102&sess=sess488"
    },
    {
      id: "tue-expanded-voices",
      date: "2026-07-21",
      start: "11:05",
      end: "11:25",
      title: "Expanded Voices",
      subtitle: "Voice cloning, latent spaces and embodied translation",
      type: "Art Paper",
      location: "411 Theatre",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Barcelona Supercomputing Center and vocalist María Arnal turn voice cloning and latent-space visualization into an interactive installation. The week's most direct hit on voice work.",
      url: "https://s2026.conference-schedule.org/presentation/?id=artpl_135&sess=sess229"
    },
    {
      id: "tue-chaos-latest",
      date: "2026-07-21",
      start: "11:00",
      end: "11:50",
      title: "What's the Latest at Chaos?",
      subtitle: "World-building, Gaussian splats and artist-friendly AI",
      type: "Industry Session",
      location: "Room 511 C",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "recommended",
      note: "A second practical Chaos session immediately after the ray-traced splat talk."
    },
    {
      id: "tue-live-from-la",
      date: "2026-07-21",
      start: "14:00",
      end: "14:20",
      title: "Live from LA!",
      subtitle: "Immersive youth theatre and personal storytelling",
      type: "Educator's Forum",
      location: "Room 501 ABC",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "UCSB and Processing Foundation researchers on an immersive youth-theatre production: dance, poetry, projection mapping and p5.js authorship.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_395&sess=sess209"
    },
    {
      id: "tue-radiance-fields",
      date: "2026-07-21",
      start: "14:30",
      end: "16:00",
      title: "Deploying Radiance Fields Across Real-Time and Web",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Discussion of shipping radiance fields in real-time and web stacks, spanning research and industry."
    },
    {
      id: "tue-lod-gaussians",
      date: "2026-07-21",
      start: "14:40",
      end: "15:40",
      title: "A LoD of Gaussians",
      subtitle: "Out-of-core training and rendering for ultra-large scenes",
      type: "Emerging Technologies Demo",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "option",
      note: "Drop-in demo of out-of-core splat training; the same work presents as a paper in Monday's 3DGS I block. Overlaps Deploying Radiance Fields."
    },
    {
      id: "tue-nurec",
      date: "2026-07-21",
      start: "15:00",
      end: "15:50",
      title: "Autonomous Vehicle Simulation with NuRec, 3D Gaussian & Cosmos",
      type: "Industry Session",
      location: "Room 502 A",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "option",
      note: "Overlaps the other two — the choice is deployment versus simulation."
    },
    {
      id: "tue-roll-reality",
      date: "2026-07-21",
      start: "15:15",
      end: "17:00",
      title: "Roll for Reality",
      subtitle: "Virtual-production improvised D&D show",
      type: "Immersive Pavilion",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "District Cinema and Epic Games run a live improvised D&D show through motion capture, AI narrative tools and real-time XR.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensubcur105&sess=sess380"
    },

    // Wednesday
    {
      id: "wed-hiring",
      date: "2026-07-22",
      start: "09:00",
      end: "10:30",
      title: "Current Hiring Trends in Animation & VFX",
      type: "Educator's Forum",
      location: "Room 501 ABC",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "The studio hiring picture across animation and VFX."
    },
    {
      id: "wed-gausmoke",
      date: "2026-07-22",
      start: "10:00",
      end: "11:00",
      title: "GauSmoke",
      subtitle: "Hybrid physics-optical Gaussian splatting for smoke reconstruction",
      type: "Emerging Technologies Demo",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Drop-in technical demo."
    },
    {
      id: "wed-splats-animation",
      date: "2026-07-22",
      start: "10:00",
      end: "11:30",
      title: "Gaussian Splatting for Animation",
      subtitle: "Emerging workflows and hybrid pipelines",
      type: "Birds of a Feather",
      location: "Room 510",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Community discussion on splat-based animation workflows. Overlaps the morning demos."
    },
    {
      id: "wed-motion-capture-society",
      date: "2026-07-22",
      start: "11:00",
      end: "12:00",
      title: "Motion Capture Society",
      type: "Birds of a Feather",
      location: "Room 512",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "Direct professional community around performance capture."
    },
    {
      id: "wed-openusd-streamed",
      date: "2026-07-22",
      start: "11:30",
      end: "12:00",
      title: "OpenUSD Streamed to Any Device",
      type: "Stage Session",
      location: "West Hall A",
      people: ["me"],
      access: ["Discover", "Experience", "Full"],
      status: "option",
      note: "Radiance-field-adjacent delivery workflow."
    },
    {
      id: "wed-virtual-theatre",
      date: "2026-07-22",
      start: "13:00",
      end: "13:45",
      title: "Virtual Theatre",
      subtitle: "Producing live theatre on virtual stages",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "The clearest crossover between live theatre production and virtual stages."
    },
    {
      id: "wed-cheap-cheerful",
      date: "2026-07-22",
      start: "14:00",
      end: "14:35",
      title: "Cheap and Cheerful",
      subtitle: "Low-fidelity prototyping for spatial stories",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Techniques for prototyping spatial stories on minimal budgets."
    },
    {
      id: "wed-refact",
      date: "2026-07-22",
      start: "15:00",
      end: "15:45",
      title: "REfact: Growing with Movement",
      subtitle: "A hybrid performance",
      type: "Spatial Storytelling",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "option",
      note: "A live hybrid movement performance. Ends before the late-afternoon conflict window."
    },
    {
      id: "wed-ai-mocap",
      date: "2026-07-22",
      start: "15:30",
      end: "17:00",
      title: "From Footage to Previs",
      subtitle: "Hands-on AI mocap workflows with Autodesk Flow Studio and Maya",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Hands-on: video footage to previs mocap in Flow Studio and Maya. Overlaps the facial-performance talks."
    },
    {
      id: "wed-show-feelings",
      date: "2026-07-22",
      start: "15:45",
      end: "17:05",
      title: "Show Your Feelings",
      subtitle: "Predator, Rigs2Emotion and Avatar facial performance",
      type: "Talks",
      location: "Room 515 A",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Three talks: Predator: Badlands emotion work, Rigs2Emotion automatic classification from facial rigs, and Wētā's case study of Varang's performance in Fire and Ash. Full badge only.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess174"
    },
    {
      id: "wed-printing",
      date: "2026-07-22",
      start: "17:25",
      end: "17:45",
      title: "Printing the Underdetermined",
      subtitle: "Materializing uncertainty through 3D Gaussian Splatting",
      type: "Art Paper",
      location: "411 Theatre",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "ShanghaiTech reconstructs multiple plausible 3D readings of figurative paintings with 3DGS, then volumetrically prints them to make the ambiguity physical.",
      url: "https://s2026.conference-schedule.org/presentation/?id=artps_121&sess=sess231"
    },

    // Thursday
    {
      id: "thu-geospatial",
      date: "2026-07-23",
      start: "09:00",
      end: "10:00",
      title: "Geospatial and 3D Tiles",
      type: "Birds of a Feather",
      location: "Room 518",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Includes discussion of large-scale geospatial content and splat delivery."
    },
    {
      id: "thu-resume-reel",
      date: "2026-07-23",
      start: "09:00",
      end: "10:00",
      title: "How to Get Your Resume & Reel Noticed",
      type: "Career development",
      location: "Room 404 AB",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "A second chance if Sunday's career session is lost to travel."
    },
    {
      id: "thu-captures-environments",
      date: "2026-07-23",
      start: "10:15",
      end: "11:45",
      title: "From 3D Captures to Simulated Digital Environments",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "NVIDIA capture-to-simulation pipeline with mixed splat/mesh physics."
    },
    {
      id: "thu-dear-neighbors",
      date: "2026-07-23",
      start: "11:15",
      end: "12:15",
      title: "Dear Upstairs Neighbors",
      subtitle: "Artist-centered, AI-assisted expressionistic animation",
      type: "Production Session",
      location: "Petree D",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Google DeepMind's animated short about a sleepless night: the director, VFX supervisor and supervising animator on masked video-to-video generation with artists in control.",
      url: "https://s2026.conference-schedule.org/presentation/?id=pros_109&sess=sess161"
    },
    {
      id: "thu-world-simulation",
      date: "2026-07-23",
      start: "12:00",
      end: "13:30",
      title: "Advance World Simulation with 3D Gaussian Splatting",
      subtitle: "Large-scale environment reconstruction",
      type: "Hands-on Course",
      location: "Concourse Hall",
      people: ["me"],
      access: ["Experience", "Full"],
      status: "anchor",
      note: "NVIDIA lab with Omniverse NuRec: multi-GPU reconstruction, object segmentation, then into Isaac Lab robotics simulation. Runs on the Experience badge.",
      url: "https://s2026.conference-schedule.org/presentation/?id=gensub_527&sess=sess265"
    },
    {
      id: "thu-educator-townhall",
      date: "2026-07-23",
      start: "12:30",
      end: "13:30",
      title: "Educator's Townhall",
      type: "Educator's Forum",
      location: "Room 409 AB",
      people: ["brother"],
      access: ["Experience", "Full"],
      status: "recommended",
      note: "Open town hall for the education community."
    },
    {
      id: "thu-3dgs-2",
      date: "2026-07-23",
      start: "14:00",
      end: "15:30",
      title: "3D Gaussian Splatting II",
      type: "Technical Papers",
      location: "Room 408 A",
      people: ["me"],
      access: ["Full"],
      status: "anchor",
      note: "Papers include 4D splatting under uncertainty, learned view-dependent kernels, Radiance Fields from Photons and reflective dual splatting. Full badge only.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess136"
    },
    {
      id: "thu-multimodal",
      date: "2026-07-23",
      start: "15:45",
      end: "17:15",
      title: "Multimodal Learning",
      subtitle: "Dialogue, generated audio and automatic dubbing",
      type: "Technical Papers",
      location: "Room 403 A",
      people: ["brother"],
      access: ["Full"],
      status: "wishlist",
      note: "Papers include MAViD audio-visual dialogue, Audio-Omni audio generation and Just-Dub-It automatic dubbing — the research edge of voice tech.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess101"
    },
    {
      id: "thu-gaussian-reconstruction",
      date: "2026-07-23",
      start: "15:45",
      end: "17:15",
      title: "Gaussian Reconstruction",
      type: "Technical Papers",
      location: "Room 408 B",
      people: ["me"],
      access: ["Full"],
      status: "anchor",
      note: "Papers include RaDe-GS depth rasterization, sparse-view GeoQuery and Inria's immediate unordered-input reconstruction, closing with an interactive discussion. Full badge only.",
      url: "https://s2026.conference-schedule.org/session/?sess=sess138"
    },

    // Friday — free day in Los Angeles
    {
      id: "fri-downtown-morning",
      date: "2026-07-24",
      start: "09:00",
      end: "11:00",
      title: "Downtown morning: Grand Central Market & The Last Bookstore",
      subtitle: "Breakfast stalls, the book labyrinth and Disney Concert Hall",
      type: "Free day",
      location: "Downtown LA",
      people: ["me", "brother"],
      access: [],
      status: "recommended",
      interest: { me: 3, brother: 2 },
      note: "Grand Central Market opens at 8:00 a.m.; The Last Bookstore's Downtown page currently lists a 10:00 a.m. Friday opening. Confirm the route once the hotel is known.",
      url: "https://grandcentralmarket.com/visit-the-market/"
    },
    {
      id: "fri-academy-museum",
      date: "2026-07-24",
      start: "11:30",
      end: "14:30",
      title: "Academy Museum of Motion Pictures",
      subtitle: "Jaws (final weekend), Greenwood/Spencer production design, Ghibli PONYO",
      type: "Free day",
      location: "Miracle Mile",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      interest: { me: 3, brother: 4 },
      note: "Jaws: The Exhibition closes Jul 26 — this is its final weekend. Book timed entry ahead. LACMA and the La Brea Tar Pits are on the same block. Either/or with the Warner Bros. tour.",
      url: "https://www.academymuseum.org/"
    },
    {
      id: "fri-warner-tour",
      date: "2026-07-24",
      start: "12:00",
      end: "15:00",
      title: "Warner Bros. Studio Tour",
      subtitle: "Working soundstages and the Burbank backlot",
      type: "Free day",
      location: "Burbank",
      people: ["me", "brother"],
      access: [],
      status: "option",
      interest: { me: 2, brother: 4 },
      note: "The either/or alternative to the Academy Museum: about one guided hour plus two self-guided hours. Advance booking required; pairs with Griffith afterward.",
      url: "https://www.wbstudiotour.com/tour/studio/"
    },
    {
      id: "fri-santa-monica",
      date: "2026-07-24",
      start: "14:00",
      end: "17:00",
      title: "Santa Monica Pier & Venice decompress",
      subtitle: "The Pacific, if Thursday emptied the tank",
      type: "Free day",
      location: "Santa Monica",
      people: ["me", "brother"],
      access: [],
      status: "option",
      interest: { me: 2, brother: 2 },
      note: "Low-energy alternative to the museum/studio afternoon; also positions closer to LAX for the Saturday 11:00 a.m. departure.",
      url: "https://www.santamonicapier.org/"
    },
    {
      id: "fri-griffith-sunset",
      date: "2026-07-24",
      start: "17:30",
      end: "20:30",
      title: "Griffith Observatory at sunset",
      subtitle: "Hollywood sign, basin panorama and golden hour",
      type: "Free day",
      location: "Griffith Park",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      interest: { me: 4, brother: 3 },
      note: "Free and open until 10:00 p.m. Sunset is 8:00 p.m. on Jul 24. Allow extra time for Friday traffic, parking or the DASH shuttle.",
      url: "https://griffithobservatory.lacity.gov/visit/"
    },
    {
      id: "fri-improv-evening",
      date: "2026-07-24",
      start: "21:30",
      end: "22:50",
      title: "Groundlings late show",
      subtitle: "Friday sketch and improv after Griffith",
      type: "Free day",
      location: "Hollywood",
      people: ["me", "brother"],
      access: [],
      status: "option",
      interest: { me: 2, brother: 4 },
      note: "The Groundlings currently lists its 80-minute late show on Fridays at 9:30 p.m. Verify Jul 24 availability before booking.",
      url: "https://groundlings.com/shows/the-completely-different-late-show"
    },

    // Saturday travel
    {
      id: "sat-return-flight",
      date: "2026-07-25",
      start: "11:00",
      end: "16:00",
      title: "Flight home · Los Angeles to Charlotte",
      subtitle: "Departs 11:00 a.m. PDT · lands 7:00 p.m. EDT",
      type: "Confirmed flight",
      location: "LAX → CLT",
      people: ["me", "brother"],
      access: [],
      status: "anchor",
      showInterest: false,
      note: "Nonstop · 5h 00m · Basic Economy. Aim for LAX by 9:00 a.m. with bags."
    }
  ]
};
